import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { TableStoreProvider } from "@/stores/table-store-provider";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <TableStoreProvider>
          <div className="h-svh">{children}</div>
        </TableStoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
